name: meteo_app
description: Une application météo Flutter pour l'examen LIAGE/ISI KM 2025.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  google_maps_flutter: ^2.7.0
  provider: ^6.1.2
  percent_indicator: ^4.2.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
